export const news = [
  {
    id: 1,
    slug: "smart-home-systems",
    image: "https://picsum.photos/200/200",
    images: [
      "https://picsum.photos/200/200",
      "https://picsum.photos/200/200",
      "https://picsum.photos/200/200",
      "https://picsum.photos/200/200",
      "https://picsum.photos/200/200",
    ],
    categories: ["business", "technology"],
    title: {
      en: "Smart home systems are becoming more and more popular",
      ru: "Системы «умный дом» становятся все более популярными",
      uz: "Smart home systems are becoming more and more popular",
    },
    date: "2023-05-05",
    content: {
      en: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras a mi tempor, mollis libero quis, cursus orci. Proin sit amet quam erat. Vestibulum congue neque et urna iaculis hendrerit. Pellentesque molestie mi nisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque dictum nec quam eu luctus. Nulla efficitur tellus et lacinia eleifend. Curabitur euismod libero nec nisl pulvinar, id ultricies risus sollicitudin. Nam placerat sed libero et imperdiet. Integer quis auctor turpis, euismod sollicitudin nisl. Maecenas scelerisque sagittis leo vel maximus. Proin consequat finibus elit, vitae tristique dolor tempor sit amet.
        Cras viverra elit eget hendrerit ultrices. Praesent elementum nibh sed finibus aliquet. Phasellus imperdiet, purus eget porta hendrerit, ante eros consectetur libero, ut ullamcorper erat lorem dignissim magna. Sed augue lacus, tempus eget semper quis, sagittis at enim. Nullam aliquam turpis erat, vel molestie ipsum fringilla in. Nulla et diam massa. Pellentesque quis eleifend nibh. Praesent placerat tellus est, quis lobortis tortor bibendum scelerisque. Aenean tellus lorem, sagittis eu molestie vel, lobortis sit amet magna. Pellentesque risus urna, pulvinar eget posuere a, dapibus vitae velit.
        Aenean sagittis semper massa eget feugiat. Duis ut erat enim. Integer eget semper tortor, quis congue ex. Phasellus gravida, leo sed maximus finibus, lectus eros venenatis orci, sed semper tortor leo quis sapien. Pellentesque sit amet erat pharetra quam accumsan fermentum tempus non mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lacinia magna et dolor consequat, vel consequat magna molestie. Cras at consectetur sem. Sed dui ex, cursus non massa interdum, lacinia bibendum nisi. Mauris vitae diam ac augue pulvinar viverra. Nulla aliquam, ligula nec sodales commodo, quam ex cursus nunc, vel ullamcorper mi ante vel metus. Curabitur nulla libero, consequat et ornare sit amet, tincidunt et ex. Vestibulum eget nisi eu ipsum posuere laoreet. Ut blandit eget elit eu tempor. Duis vehicula laoreet nibh vitae dignissim. Ut elementum ante vitae dui tempus ultrices. Nam egestas feugiat sapien a blandit. Duis purus nulla, dignissim ut ante non, sagittis vestibulum nisl. Praesent condimentum blandit augue, sed dapibus dui pulvinar a. Aenean lobortis sapien gravida leo aliquam, eu mollis risus fermentum. Fusce dictum nec libero at pellentesque. Nam sem libero, tincidunt et hendrerit id, suscipit sed neque. Sed hendrerit metus mauris, vitae feugiat risus mattis at. Morbi convallis luctus nibh, vel consectetur velit cursus vel. Sed aliquet aliquet augue quis tincidunt. Proin fringilla nec massa in egestas. Nullam consequat est quis dui consequat iaculis. Maecenas condimentum rhoncus mollis.`,
      ru: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras a mi tempor, mollis libero quis, cursus orci. Proin sit amet quam erat. Vestibulum congue neque et urna iaculis hendrerit. Pellentesque molestie mi nisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque dictum nec quam eu luctus. Nulla efficitur tellus et lacinia eleifend. Curabitur euismod libero nec nisl pulvinar, id ultricies risus sollicitudin. Nam placerat sed libero et imperdiet. Integer quis auctor turpis, euismod sollicitudin nisl. Maecenas scelerisque sagittis leo vel maximus. Proin consequat finibus elit, vitae tristique dolor tempor sit amet.
        Cras viverra elit eget hendrerit ultrices. Praesent elementum nibh sed finibus aliquet. Phasellus imperdiet, purus eget porta hendrerit, ante eros consectetur libero, ut ullamcorper erat lorem dignissim magna. Sed augue lacus, tempus eget semper quis, sagittis at enim. Nullam aliquam turpis erat, vel molestie ipsum fringilla in. Nulla et diam massa. Pellentesque quis eleifend nibh. Praesent placerat tellus est, quis lobortis tortor bibendum scelerisque. Aenean tellus lorem, sagittis eu molestie vel, lobortis sit amet magna. Pellentesque risus urna, pulvinar eget posuere a, dapibus vitae velit.
        Aenean sagittis semper massa eget feugiat. Duis ut erat enim. Integer eget semper tortor, quis congue ex. Phasellus gravida, leo sed maximus finibus, lectus eros venenatis orci, sed semper tortor leo quis sapien. Pellentesque sit amet erat pharetra quam accumsan fermentum tempus non mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lacinia magna et dolor consequat, vel consequat magna molestie. Cras at consectetur sem. Sed dui ex, cursus non massa interdum, lacinia bibendum nisi. Mauris vitae diam ac augue pulvinar viverra. Nulla aliquam, ligula nec sodales commodo, quam ex cursus nunc, vel ullamcorper mi ante vel metus. Curabitur nulla libero, consequat et ornare sit amet, tincidunt et ex. Vestibulum eget nisi eu ipsum posuere laoreet. Ut blandit eget elit eu tempor. Duis vehicula laoreet nibh vitae dignissim. Ut elementum ante vitae dui tempus ultrices. Nam egestas feugiat sapien a blandit. Duis purus nulla, dignissim ut ante non, sagittis vestibulum nisl. Praesent condimentum blandit augue, sed dapibus dui pulvinar a. Aenean lobortis sapien gravida leo aliquam, eu mollis risus fermentum. Fusce dictum nec libero at pellentesque. Nam sem libero, tincidunt et hendrerit id, suscipit sed neque. Sed hendrerit metus mauris, vitae feugiat risus mattis at. Morbi convallis luctus nibh, vel consectetur velit cursus vel. Sed aliquet aliquet augue quis tincidunt. Proin fringilla nec massa in egestas. Nullam consequat est quis dui consequat iaculis. Maecenas condimentum rhoncus mollis.`,
      uz: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras a mi tempor, mollis libero quis, cursus orci. Proin sit amet quam erat. Vestibulum congue neque et urna iaculis hendrerit. Pellentesque molestie mi nisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque dictum nec quam eu luctus. Nulla efficitur tellus et lacinia eleifend. Curabitur euismod libero nec nisl pulvinar, id ultricies risus sollicitudin. Nam placerat sed libero et imperdiet. Integer quis auctor turpis, euismod sollicitudin nisl. Maecenas scelerisque sagittis leo vel maximus. Proin consequat finibus elit, vitae tristique dolor tempor sit amet.
        Cras viverra elit eget hendrerit ultrices. Praesent elementum nibh sed finibus aliquet. Phasellus imperdiet, purus eget porta hendrerit, ante eros consectetur libero, ut ullamcorper erat lorem dignissim magna. Sed augue lacus, tempus eget semper quis, sagittis at enim. Nullam aliquam turpis erat, vel molestie ipsum fringilla in. Nulla et diam massa. Pellentesque quis eleifend nibh. Praesent placerat tellus est, quis lobortis tortor bibendum scelerisque. Aenean tellus lorem, sagittis eu molestie vel, lobortis sit amet magna. Pellentesque risus urna, pulvinar eget posuere a, dapibus vitae velit.
        Aenean sagittis semper massa eget feugiat. Duis ut erat enim. Integer eget semper tortor, quis congue ex. Phasellus gravida, leo sed maximus finibus, lectus eros venenatis orci, sed semper tortor leo quis sapien. Pellentesque sit amet erat pharetra quam accumsan fermentum tempus non mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lacinia magna et dolor consequat, vel consequat magna molestie. Cras at consectetur sem. Sed dui ex, cursus non massa interdum, lacinia bibendum nisi. Mauris vitae diam ac augue pulvinar viverra. Nulla aliquam, ligula nec sodales commodo, quam ex cursus nunc, vel ullamcorper mi ante vel metus. Curabitur nulla libero, consequat et ornare sit amet, tincidunt et ex. Vestibulum eget nisi eu ipsum posuere laoreet. Ut blandit eget elit eu tempor. Duis vehicula laoreet nibh vitae dignissim. Ut elementum ante vitae dui tempus ultrices. Nam egestas feugiat sapien a blandit. Duis purus nulla, dignissim ut ante non, sagittis vestibulum nisl. Praesent condimentum blandit augue, sed dapibus dui pulvinar a. Aenean lobortis sapien gravida leo aliquam, eu mollis risus fermentum. Fusce dictum nec libero at pellentesque. Nam sem libero, tincidunt et hendrerit id, suscipit sed neque. Sed hendrerit metus mauris, vitae feugiat risus mattis at. Morbi convallis luctus nibh, vel consectetur velit cursus vel. Sed aliquet aliquet augue quis tincidunt. Proin fringilla nec massa in egestas. Nullam consequat est quis dui consequat iaculis. Maecenas condimentum rhoncus mollis.`,
    },
  },
];
